name: CD
on:
  push:
    branches:
      - '**'
jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Run Linter
        run: npm run lint
      - name: Run Prettier
        run: npm run prettier
      - name: Run Tests
        run: npm run test
  build:
    name: Build
    needs: [verify]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Next.js Build & Export
        run: npm run build
