name: Next.js Linter
on: 
  pull_request:
    branches:
      - main
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Where am I?
        run: pwd
      - name: Install Dependencies
        run: npm install
      - name: Run Linter
        run: npm run lint
