name: Next.js Linter
on: 
  pull_request:
    branches:
      - main
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run Linter
        run: |
          cd ${{ github.workspace }}
          npm run lint
